language: node_js
node_js: "stable"

cache: 
  directories:
    - node_modules

script:
  - npm test

env:
  - CI=true

after_success:
  - npm run coverage

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
   - chmod +x ./scripts/deploy.sh
   - ./scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: develop