export const FETCH_RIDE_REQUESTS_SUCCESS = 'FETCH_RIDE_REQUESTS_SUCCESS';
export const FETCH_RIDE_REQUESTS_LOADING = 'FETCH_RIDE_REQUESTS_LOADING';
export const FETCH_RIDE_REQUESTS_ERROR = 'FETCH_RIDE_REQUESTS_ERROR';
